version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "gogs"
      - "registry"
    volumes:
      # - ./VOLUMES/nginx/webs:/usr/share/nginx/html
      - ./VOLUMES/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./VOLUMES/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./VOLUMES/nginx/sites-enable:/etc/nginx/sites-enable
      - ./VOLUMES/nginx/sites-ssl:/etc/nginx/ssl
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker
    command: bash -c "chown -R root:root /etc/nginx/ssl; chmod -R 600 /etc/nginx/ssl && exec nginx -g 'daemon off;'"

  nexus:
    image: sonatype/nexus3:latest
    restart: always
    volumes:
      - ./VOLUMES/nexus/NEXUS_DATA:/nexus-data
    ports:
      - '8081:8081'

  jenkins:
    image: kmikodev/jenkins-dind:0.0.1
    restart: always
    ports:
      - 8080:8080
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./VOLUMES/jenkins/JENKINS_HOME:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./VOLUMES/registry/data:/var/lib/registry
      - ./VOLUMES/registry/certs:/certs
      - ./VOLUMES/registry/auth:/auth

  gogsData:
    image: 'busybox'
    tty: true
    volumes:
      - './VOLUMES/gogs/data:/data'
      - './VOLUMES/gogs/mysql:/var/lib/mysql'

  gogs:
    image: gogs/gogs
    restart: 'always'
    ports:
      - '22:22'
      - '3000:3000'
    links:
      - jenkins
    volumes_from:
      - 'gogsData'

  mysql:
    image: mariadb:10.1
    restart: 'always'
    volumes_from:
      - 'gogsData'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: kmiko
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: kmiko

volumes:
  nexus:
  jenkins:
  nginx:
  db-data:
    driver: local
